#ifndef CREDENTIALS_H
#define CREDENTIALS_H

#define WIFI_SSID               "YOUR_WIFI_SSID_HERE"
#define WIFI_PASSWORD           "YOUR_WIFI_PASSWORD_HERE"

#define FIREBASE_DATABASE_URL   "YOUR_FIREBASE_DATABASE_URL_HERE"
#define FIREBASE_WEBAPI_KEY     "YOUR_FIREBASE_WEB_API_KEY_HERE"
#define FIREBASE_STORAGE_BUCKET "YOUR_FIREBASE_STORAGE_BUCKET_HERE"

#define DEVICE_EMAIL            "YOUR_DEVICE_EMAIL_HERE"
#define DEVICE_PASSWORD         "YOUR_DEVICE_PASSWORD_HERE"
#define USER_UID                "YOUR_USER_UID_HERE"

#endif // CREDENTIALS_H
